### ISSUE TITLE
Use of MKL in NEMSIO library

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/NCEPLIBS-nemsio#15]
https://github.com/NOAA-EMC/NCEPLIBS-nemsio/blob/caeb76ab34ac251888417a2c2afc997b7859755e/src/CMakeLists.txt#L11

Can someone clarify the use of MKL in the NEMSIO library?

**Comment by junwang-noaa** [comment]
I haven not worked on nemsio file a while, but I don't think we have that before, nemsio lib itself does not need mkl.

**Comment by aerorahul** [comment]
@junwang-noaa  Thanks for the quick confirmation.

**Comment by kgerheiser** [comment]
We got rid of it
