### ISSUE TITLE
ufs_release_v1.0: Inconsistent naming of include directory and library name

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/NCEPLIBS-nemsio#4]
When I build and install nemsio library I get this directory structure in the install location.
```
├── include_4
│   ├── nemsio_module.mod
│   ├── nemsio_module_mpi.mod
│   ├── nemsio_openclose.mod
│   ├── nemsio_read.mod
│   └── nemsio_write.mod
└── lib
    └── libnemsio_v2.2.3.a
```
The name of the include directory with _4 suffix is used in cases when we provide libraries compiled with multiple precisions (*_4 *_d and *_8). This is not the case here. There's only one library built here.  The include directory should not have _4 suffix.

**Comment by climbfuji** [comment]
I assume you refer to the ufs_release_1.0 branch? If so, this was my mistake and I will fix it on Monday. Sorry!

**Comment by DusanJovic-NOAA** [comment]
> I assume you refer to the ufs_release_1.0 branch? If so, this was my mistake and I will fix it on Monday. Sorry!

Yes, I refer to ufs_release_v1.0 branch, as indicated in the title.

**Comment by DusanJovic-NOAA** [comment]
Fixed  in https://github.com/NOAA-EMC/NCEPLIBS-nemsio/pull/5
